# This is a basic workflow to help you get started with Actions

name: CI-CD-Pipeline-to AWS-ElsticBeanStalk
env:
  EB_PACKEGE_S3_BUCKET_NAME: "my-new-flask-application-packege"
  EB_APPLICATION_NAME      : "MyFlask"
  EB_ENVIRONMENT_NAME      : "MyFlask-env"
  DEPLOY_PACKEGE_NAEM      : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME          :  "eu-central-1"
on:
  push:
    branches: [ master ]

jobs:
  my_ci_part:
    runs-on: ubuntu-latest
    
    
    steps:
    - name: Git clone our repo
      uses: actions/checkout@v1

    - name: Create clone our repo
      run:  zip -r ${{ env.DEPLOY_PACKEGE_NAME }} ./ -x *.git
